apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limits
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
    min:
      storage: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limits
spec:
  limits:
  - max:
      cpu: "1000m"
    defaultRequest:
      cpu: "100m"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limits
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 128Mi
    type: Container