{{- if (.Values.persistentVolume).enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "service-chart.fullname" . }}-pv"
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: "{{ .Values.persistentVolume.capacity | default "1Gi" }}"
  accessModes:
    - ReadWriteOnce # The volume can be mounted as read-write by a single node.
  hostPath:
    path: {{ .Values.persistentVolume.mountPath }} # This is an example path on the host

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "service-chart.fullname" . }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: ssd # if for some reason you need faster, more expensive storage
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.capacity | default "1Gi" }}"
{{- end }}