---
image:
  repository: gcr.io/bolsterlab/lab/hello-world
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
persistentVolume:
  enabled: true
  path: /mnt/data
  capacity: 1Gi
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: hello.lab.bolster.online
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts: [hello.lab.bolster.online]
      secretName: lab-bolster-online-tls
