---
name: Example CI/CD Pipeline for Hello World App
# on:
#   push:
#     branches: [main]
on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed
env:
  SERVICE_NAME: hello-world  # container name, should normally be {{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Google Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: '${{ secrets.GCR_JSON_KEY }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:hello_world.example"
          file: ./build/Dockerfile  # path to Dockerfile, should standardise to build/Dockerfile for all services
          push: true
          tags: gcr.io/bolsterlab/${{ env.SERVICE_NAME }}:${{ github.sha }}
      - name: Deploy to GKE
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        working-directory: hello_world.example  # THIS SHOULDN'T BE NECESSARY IN A REAL PROJECT
        run: |-
          helm upgrade --install  ${{ env.SERVICE_NAME }} ./service-chart \
          --set image.repository=gcr.io/bolsterlab/${{ env.SERVICE_NAME }} \
          --set image.tag=${{ github.sha }} \
          --values ./values.yaml
